### PR TITLE
Update coi.cgi

### PR DESCRIPTION
**Pull request by clr-apache**
Add time zone to date field in submitted document

### CODE REVIEW

**Comment by sebbASF** [comment]
AFAIK the server runs on UTC, so it will always show +00:00, but I agree that displayed times should include the TZ for

**Comment by rubys** [comment]
Example output, when run on whimsy-vm6:

```
rubys@whimsy-vm6:~$ ruby -r date -e 'p DateTime.now.strftime "%Y-%m-%d %H:%M:%S %:z"'
"2022-04-23 12:15:59 +00:00"
```

**Review by sebbASF — APPROVED** [review]
OK by me

**Comment by clr-apache** [comment]
If the server runs on utc how do I get the user's time zone? Does the server know it or would the message have to include it?

**Comment by sebbASF** [comment]
The web browser knows the time zone it has been told by the user, but I don't think it passes this on to the server.
Why is the user TZ needed?

**Comment by clr-apache** [comment]
The user time zone enhances the non-repudiability of the generated timestamp. But at least having the time zone of the time stamp helps anyone looking at the document to understand the actual timestamp.

**Pull request merged**
